

FROM python:3.11-slim

WORKDIR /usr/app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir psycopg2-binary dbt-postgres==1.8.0 dbt-core==1.8.0

ENTRYPOINT ["dbt"]
CMD ["run"]