

olist_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('OLIST_DB_HOST', 'olist-db') }}"
      port: "{{ env_var('OLIST_DB_PORT', '5432') | as_number }}"
      user: "{{ env_var('OLIST_DB_USER', 'olist') }}"
      pass: "{{ env_var('OLIST_DB_PASS', 'olist') }}"
      dbname: "{{ env_var('OLIST_DB_NAME', 'olist') }}"
      schema: public
      threads: 4